### ISSUE TITLE
Segfault in glfwGetVideoModes()

### ISSUE THREAD

**Issue by landersson** [rougier/pyglfw#6]
Hi, first of all, thanks for maintaining this wrapper. I just tried to get full screen mode working under Mac OS X (El Capitan) and I'm getting a segfault when trying to use the monitor information functions. This python code will crash:

`import glfw`
`glfw.glfwInit()`
`monitor = glfw.glfwGetPrimaryMonitor()`
`print("Monitor:", monitor, type(monitor))`
`print(glfw.glfwGetVideoModes(monitor))`

This will print:

`Monitor: 441455392 <class 'int'>`
`Segmentation fault: 11`

I'm finding it a bit strange that monitor is listed with type 'int'... shouldn't it be size_t or similar?

The equivalent C++ code works fine. I'll try it on a 64 bit Linux machine tomorrow.

**Comment by rougier** [comment]
Yep, I got the same error.  It should return a GLFW monitor ans so the return type shoudl be specified.
```
glfwGetPrimaryMonitor           = _glfw.glfwGetPrimaryMonitor
glfwGetPrimaryMonitor.restype   = POINTER(GLFWmonitor)
```

Could you test it and make a PR if this works ?

**Comment by landersson** [comment]
Still getting a segfault and the same output, i.e monitor is still an 'int'.

**Comment by landersson** [comment]
Just tested it on 64 bit Ubuntu 14.04... still says monitor is an 'int', but otherwise seems to work fine.

**Comment by landersson** [comment]
Sorry, typo in my application of your suggested fix... adding the correct restype does indeed fix the problem. PR sent.
