### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JusticeOF666** [rougier/pyglfw#8]
What file should _glfw_file point to?
_glfw = ctypes.CDLL(_glfw_file)

Or the GLFW_LIBRARY system variable if you will.

**Comment by rougier** [comment]
Depending on your system, it should point to the library binary (.so .dylib or .dll)

**Comment by JusticeOF666** [comment]
I seem only be able to find source and header files, not the dll's.
Any clue where I can find them/generate them?
Until now I only used the headers for my apps.

**Comment by rougier** [comment]
What is your system ? Do you know if glfw3 has been installed ?

**Comment by JusticeOF666** [comment]
Yes it is installed, at least it is build so I could use it with C.
I'm looking for DLL compilation atm. I've been able to locate a static lib file named  libglfw3.a but this doesn't work for CDLL function, of course.
I'll update ASAP.

OS Name	Microsoft Windows 10 Pro
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 4001 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by JusticeOF666** [comment]
I got it, downloadable from the website as additional binary,
Thank you, this can be closed.

**Comment by rougier** [comment]
Good !
